### ISSUE TITLE
V3.2 breaks reading and writing code, is this so important to break backward compatbility?

### ISSUE THREAD

**Issue by nicost** [micro-manager/NDTiffStorage#138]
The change from axis indices being integers to allowing all objects breaks code working with NDTiffStorage.  It makes writing (backward compatible) code to work with NDTiffStorage difficult and awkward.  Would it not be much easier to stick to integers as axis indices, and provide an  (optional) dictionary mapping indices to Objects (or highly preferable, just Strings) in summary metadata?

At the very least, according to Semver this should be a major version increase, i.e. 4.0 rather than 3.2.

**Comment by nicost** [comment]
> Can you give an example of what is broken? MDAs seem to run fine for me with the latest nightly build, and there's no problem with the tests in pycromanager that test NDTiff reading and writing. The switch to v3.2 was also 8 months ago...Is this the first time you've tried NDTiff since then?

Ran into this while researching https://github.com/micro-manager/micro-manager/issues/1807 and trying to open the subfolders using the Micro-Manager NDTiffReader.  In retrospect, I guess this means that Micro-Manager can only read the subset of NDTiffs saved by Micro-manager.  That seems a little sad.  I guess I could add code to translate channels that are saved as a String, as well as do heuristics to translate col and rows to position labels and back, but I am not quite sure where that will end or what that will bring.  

> As for why Objects is used, this is because there's no way in Java (that I know of) to have a StringOrInteger object. 

Can you use an overloaded function?  There is nothing (in the code) that makes clear that it is only String or Integer.  Enforcing this through code seems important.  Is it not much simpler to completely switch to using Strings? You can always encode an Integer in a String.

> 3.2 refers to the version of the format itself. Since string or integer keys are a superset of only integer keys, this should not break backwards compatibility on the format. 

But that does mean that a reader that can read version 3.0 can not necessarily read 3.2 files.  I do not care much one way or another, but things do seem to break here so often, which makes maintenance difficult.

**Comment by henrypinkard** [comment]
> Can you use an overloaded function? 

I don't think so because then you'd have to be all Strings or all Integers.


> > 3.2 refers to the version of the format itself. Since string or integer keys are a superset of only integer keys, this should not break backwards compatibility on the format.
> 
> But that does mean that a reader that can read version 3.0 can not necessarily read 3.2 files.

Possibly. Unclear to me that forwards incompatibility warrants a major version bump like backwards, but in any case I think its more confusing to do this now well after the fact.

>  I do not care much one way or another, but things do seem to break here so often, which makes maintenance difficult.

I don't know if I'd call once in 8 months "so often", especially during a period in which its being integrated with many other parts of MM, but depends on your perspective I guess

> Is it not much simpler to completely switch to using Strings? You can always encode an Integer in a String.

This will change the behavior on the reader side, because the axes gets serialized to JSON, which treats strings and integers differently. This definitely _would_ break a lot of stuff, so the `Object` way seemed like the least disruptive way to add the new functionality


> Ran into this while researching [micro-manager/micro-manager#1807](https://github.com/micro-manager/micro-manager/issues/1807) and trying to open the subfolders using the Micro-Manager NDTiffReader. 

It's not really the intended usage to open resolution levels individually. You should be able to get them by just passing the top-level directory of all resolution levels and then querying (and its fast enough that there shouldn't be a performance penalty). The pyramid format is admittedly a hacky design in retrospect.

> In retrospect, I guess this means that Micro-Manager can only read the subset of NDTiffs saved by Micro-manager. That seems a little sad. I guess I could add code to translate channels that are saved as a String, as well as do heuristics to translate col and rows to position labels and back, but I am not quite sure where that will end or what that will bring.

Sounds like this is the case for now, but doesn't necessarily have to remain that way. You seem to be testing things that have not been tested before. I think adding a translation layer for strings to ints is a reasonable thing to do. Would you need to do this for rows and cols though? `Coords` supports arbitrary axis names, right? So you can just keep them as is I would think

**Comment by ieivanov** [comment]
In case this is still relevant, I do really like the string-valued axes, particularly when it comes to positions with meaningful names: https://github.com/micro-manager/pycro-manager/issues/575. I had found that (at least at the time) pycromanager had no other good way of carrying that metadata.

**Comment by nicost** [comment]
Very related question: is there an API call to get out all the Objects (per axis) that have been used in a dataset?  Without that information how does one read a dataset?

**Comment by henrypinkard** [comment]
[   public Set<HashMap<String, Object>> getAxesSet();](https://github.com/micro-manager/NDTiffStorage/blob/18fc782ddd6758d23d3996a7aa46c514b7f4b35a/java/src/main/java/org/micromanager/ndtiffstorage/NDTiffAPI.java#L153)

**Comment by nicost** [comment]
Set of a HashMap?  How do I get the Objects per axis out of that?

**Comment by henrypinkard** [comment]
You're saying, for example, you want all of the Z indices that have been put into the dataset (regardless of the other axis names)?

Some like this (I didn't test it):

```java
Set<HashMap<String, Object>> axesSet = storage.getAxesSet();

      Set<Integer> zPositions = new HashSet<Integer>()
      for (HashMap<String, Object> axes : axesSet) {
         Integer zPos = axes.get("Z");
         zPositions.add(z);
      }
      return zPositions;
   }
```
